In [1]:
import numpy as np

In [2]:
a = np.array([1,1,1,1,1])

In [3]:
np.sqrt(4)

2.0

In [4]:
for i in reversed(range(4)):
    print(i)

3
2
1
0


In [5]:
import numpy as np

In [6]:
a = np.array([1,0,0,0,0,1,1,1])

np.asarray(np.where(a==1))[0]

array([0, 5, 6, 7], dtype=int64)

In [7]:
np.max([0,1])

1

In [18]:
number = np.array([[1]])
number.shape
np.squeeze(number).shape

()

In [9]:
k = np.ones((4,3))
np.sum(k, axis = 0, keepdims=True)

array([[4., 4., 4.]])

In [10]:
k

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
a = np.array([[1, 0, 1, 0, 1]])

In [12]:
a[0, 0]

1

In [13]:
np.where(a==1)

(array([0, 0, 0], dtype=int64), array([0, 2, 4], dtype=int64))

In [14]:
mislabeled_indeces = np.asarray(np.where(a==1))

In [15]:
np.where(a==1)

(array([0, 0, 0], dtype=int64), array([0, 2, 4], dtype=int64))

In [16]:
mislabeled_indeces[1][1]

2

In [26]:
b = np.array([[1, 2, 3, 4, 5]])
b.shape
np.squeeze(b).shape

(5,)